name: Dump reusable workflow contexts

on:
  workflow_call:
    inputs:
      resuableInput:
        description: 'Field for reusable workflow'
        required: false
        type: string
      shadowedInput:
        description: 'Field with same name as top-level workflow'
        required: false
        type: string

jobs:
  dump-contexts:
    runs-on: ubuntu-latest
    steps:
      - name: Dump contexts as JSON
        run: |
          # Note: reusable workflows also have a "jobs" context, but it is not
          # available here.
          cat <<'EOF' | jq --sort-keys .
          {
            "github": ${{toJSON(github)}},
            "vars": ${{toJSON(vars)}},
            "job": ${{toJSON(job)}},
            "steps": ${{toJSON(steps)}},
            "runner": ${{toJSON(runner)}},
            "secrets": ${{toJSON(secrets)}},
            "strategy": ${{toJSON(strategy)}},
            "matrix": ${{toJSON(matrix)}},
            "needs": ${{toJSON(needs)}},
            "inputs": ${{toJSON(inputs)}}
          }
          EOF
